[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
libs = ["node_modules", "lib"]
solc_version = "0.8.25"
auto_detect_remappings = false
code_size_limit = 100000
evm_version = "cancun"

[profile.default.rpc_endpoints]
arbitrum_sepolia = "https://arb-sepolia.g.alchemy.com/v2/rjATHv5NutxS6nUQp2ra1"
ethereum_sepolia = "${ETHEREUM_SEPOLIA_RPC}"

[profile.default.etherscan]
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
ethereum_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
